Feat/remove response
luigifsl/tretori-backend pull request #20
Opened 2022-09-13 06:07 UTC by ArthurPieri

2022-09-15 01:39 UTC, douglasyokoyama requested changes

2022-09-15 01:39 UTC, douglasyokoyama commented on src/domains/core/access/access.service.ts
> +    try {
Geralmente a remoção não retorna nenhum valor, dado que o item irá ser removido, tem algum motivo específico para retornar o access?

2022-09-15 01:39 UTC, douglasyokoyama commented on src/domains/core/contract/contract.controller.ts
> +  remove(@Param('id') id: number): Promise<Contract> {
Mesma dúvida do acesso aqui, tem algum motivo específico para retornar o contrato ao removê-lo?

2022-09-15 01:39 UTC, douglasyokoyama commented on src/domains/insurance/insurance.controller.ts
> +  remove(@Param('id') id: number): Promise<Insurance> {
Mesma dúvida sobre a remoção de item aqui na entidade de insurance

2022-09-15 01:39 UTC, douglasyokoyama commented on test/domains/insurance/insurance.e2e-spec.ts
> +  // Teste para criação da rota de update
Uma sugestão aqui, evitar subir código comentado, remove o código comentado, commita e depois retorna ele para ficar salvo nos seus TODOS novamente.

2022-09-15 15:05 UTC, ArthurPieri commented on src/domains/core/access/access.service.ts
> +    try {
Então, essa função de remove do repository retorna a Entity, só por isso.

2022-09-15 15:05 UTC, ArthurPieri commented on src/domains/core/contract/contract.controller.ts
> +  remove(@Param('id') id: number): Promise<Contract> {
A função remove retorna Promise<entity>

2022-09-15 15:06 UTC, ArthurPieri commented on src/domains/insurance/insurance.controller.ts
> +  remove(@Param('id') id: number): Promise<Insurance> {
mesmo que as anteriores

2022-09-15 15:06 UTC, ArthurPieri commented on test/domains/insurance/insurance.e2e-spec.ts
> +  // Teste para criação da rota de update
Não entendi

2022-09-15 18:53 UTC, douglasyokoyama commented on test/domains/insurance/insurance.e2e-spec.ts
> +  // Teste para criação da rota de update
tipo em vez de subir a alteração do comentário podia ter mantido só o // TODO - test update

2022-09-15 18:54 UTC, douglasyokoyama approved these changes

2022-09-15 19:27 UTC, douglasyokoyama approved these changes, later dismissed

2022-09-16 00:44 UTC, luigifsl commented on test/domains/insurance/insurance.e2e-spec.ts
> +  // Teste para criação da rota de update
Deixa a alteração local ao inves de commitar no PR.

2022-09-16 00:44 UTC, luigifsl submitted a review, later dismissed

2022-09-16 02:21 UTC, ArthurPieri commented on test/domains/insurance/insurance.e2e-spec.ts
> +  // Teste para criação da rota de update
Entendi

2022-09-20 14:32 UTC, luigifsl commented on src/domains/core/access/access.service.ts
> +    await this.accessRepository.remove(access)
Quando vc usa await nao precisa usar os metodos `then` e `catch`. Nesse caso vc utilizaria um `try/catch`.

2022-09-20 14:33 UTC, luigifsl commented on src/domains/core/contract/contract.service.ts
> +    await this.contractRepository.remove(contract)
Mesma coisa aqui.

2022-09-26 12:43 UTC, luigifsl commented on src/domains/insurance/insurance.service.ts
>      const oldInsurance = await this.findOne(id)
Essa linha deveria estar dentro do try catch

2022-09-26 12:48 UTC, luigifsl approved these changes

2022-09-27 02:53 UTC, merged

2022-09-27 02:53 UTC, ArthurPieri commented on src/domains/insurance/insurance.service.ts
>      const oldInsurance = await this.findOne(id)
Então é pq como já estou tratando o erro na findOne, achei que não precisava